services:
  - type: web
    name: bneera
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_EMAILS
        sync: false
      - key: DB_PATH
        value: /data/data.sqlite
      - key: UPLOAD_DIR
        value: /data/uploads
    disk:
      name: bneera-data
      mountPath: /data
      sizeGB: 1
